pub const STORAGE_KEY: &str = "YOUR STORAGE ACCOUNT KEY";
pub const STORAGE_CONTAINER: &str = "YOUR CONTAINER NAME";
pub const STORAGE_BLOB: &str = "YOUR BLOB NAME";
pub const STORAGE_ACCOUNT: &str = "YOUR STORAGE ACCOUNT NAME";
