[package]
name = "azure_uploader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
azure_blob_uploader = "0.1.0"
tokio = { version = "1.33.0", features = ["full"] }
